config :bespin,
  :required => [:tiki, :'tiki/system', 
    :"sproutcore",
    :"sproutcore/empty_theme", 
    :"sproutcore/standard_theme"],
  :test_required => [:core_test],
  :use_modules => true,
  :use_loader => true,
  :factory_format => :function,
  :load_tests => true

