config :bespin,
  :required => [:tiki, :'tiki/system',
    :core_test, 
    :"sproutcore",
    :"sproutcore/empty_theme", 
    :"sproutcore/standard_theme"],
  :use_modules => true,
  :use_loader => true,
  :factory_format => :function,
  :load_tests => true

